Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: "UserPool-${self:provider.stage}"
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: "UserPoolClient-${self:provider.stage}"
      UserPoolId:
        Ref: CognitoUserPool
      GenerateSecret: false
