# src/resources/function-configurations.yml
getMyDwelling:
  handler: src/resolvers/dwelling/js-dwelling-resolvers.js
  dataSource: DynamoDBDataSource

search:
  handler: src/resolvers/js-search-resolver.js
  dataSource: DynamoDBDataSource

uploadRoomImage:
  handler: src/resolvers/room/js-room-image-resolver.js
  dataSource: NoneDataSource

imageProcessor:
  handler: src/utils/image-processor.js
  memorySize: 1024
  timeout: 60
  events:
    - s3:
        bucket: ${self:provider.environment.IMAGE_BUCKET}
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploads/
          - suffix: .jpg