Resources:
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:provider.environment.IMAGE_BUCKET}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
