version: 0.2

phases:
  install:
    commands:
      - npm install -g serverless
      - npm install -g newman
  post_build:
    commands:
      - npm install
      - serverless deploy --region eu-west-2 --verbose
      - newman run postman/hopo-dwelling.postman_collection.json -r json --reporter-json-export ./report.json

artifacts:
  files:
    - report.json