version: 0.2

phases:
  install:
    commands:
      - npm install -g serverless
      - npm install -g newman
  post_build:
    commands:
      - npm install
      - serverless deploy --region eu-west-2 --verbose
      - newman run postman/hopo-all.postman_collection.json -r json,cli --reporter-json-export ./report.json
      - aws s3 cp ./report.json s3://hopo-codebuild-artifacts/hopo-blue/report-`date +"%y%m%d%H%M"`.json